/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _danielng23_dsh_xry_host_system_metrics_systemMetrics_listDirectory_parameter_0$schema = z.string()
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_listDirectory_result$schema = z.object({
  'path': z.string().readonly(),
  'entries': z.array(z.object({
  'name': z.string().readonly(),
  'isDirectory': z.boolean().readonly(),
})).readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
})
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_overview_result$schema = z.object({
  'timestamp': z.number().readonly(),
  'platform': z.string().readonly(),
  'uptimeSeconds': z.number().readonly(),
  'loadavg': z.tuple([z.number(), z.number(), z.number()]).readonly(),
  'memory': z.object({
  'totalBytes': z.number().readonly(),
  'usedBytes': z.number().readonly(),
}).readonly(),
  'swap': z.object({
  'totalBytes': z.number().readonly(),
  'usedBytes': z.number().readonly(),
}).readonly(),
  'cores': z.array(z.object({
  'user': z.number().readonly(),
  'nice': z.number().readonly(),
  'sys': z.number().readonly(),
  'idle': z.number().readonly(),
  'irq': z.number().readonly(),
})).readonly(),
  'thermalLevel': z.union([z.literal(null), z.number()]).readonly(),
  'powerState': z.union([z.literal(null), z.string()]).readonly(),
  'hardware': z.object({
  'manufacturer': z.string().readonly(),
  'model': z.string().readonly(),
  'chassis': z.string().readonly(),
}).readonly(),
  'tasks': z.number().readonly(),
  'processes': z.array(z.object({
  'pid': z.number().readonly(),
  'name': z.string().readonly(),
  'cpuPct': z.number().readonly(),
  'memPct': z.number().readonly(),
})).readonly(),
  'network': z.object({
  'interfaceName': z.string().readonly(),
  'state': z.string().readonly(),
  'ip': z.union([z.literal(null), z.string()]).readonly(),
  'pingMs': z.union([z.literal(null), z.number()]).readonly(),
  'rxBytes': z.number().readonly(),
  'txBytes': z.number().readonly(),
}).readonly(),
  'storage': z.object({
  'path': z.string().readonly(),
  'totalBytes': z.number().readonly(),
  'usedBytes': z.number().readonly(),
  'usedPct': z.number().readonly(),
}).readonly(),
})
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_readFile_parameter_0$schema = z.string()
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_readFile_result$schema = z.object({
  'path': z.string().readonly(),
  'kind': z.union([z.literal("text"), z.literal("image"), z.literal("video"), z.literal("unsupported")]).readonly(),
  'mime': z.string().readonly(),
  'sizeBytes': z.number().readonly(),
  'truncated': z.boolean().readonly(),
  'text': z.union([z.literal(null), z.string()]).readonly(),
  'dataUrl': z.union([z.literal(null), z.string()]).readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
})
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_runCommand_parameter_0$schema = z.string()
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_runCommand_result$schema = z.object({
  'stdout': z.string().readonly(),
  'stderr': z.string().readonly(),
  'exitCode': z.union([z.literal(null), z.number()]).readonly(),
})
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_snapshot_result$schema = z.object({
  'loadavg': z.tuple([z.number(), z.number(), z.number()]).readonly(),
  'cpuBusyRatio': z.number().readonly(),
  'totalMemoryBytes': z.number().readonly(),
  'freeMemoryBytes': z.number().readonly(),
  'uptimeSeconds': z.number().readonly(),
  'timestamp': z.number().readonly(),
})
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_writeFile_parameter_0$schema = z.string()
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_writeFile_parameter_1$schema = z.string()
const _danielng23_dsh_xry_host_system_metrics_systemMetrics_writeFile_result$schema = z.object({
  'path': z.string().readonly(),
  'sizeBytes': z.number().readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
})

export const TYPERT = {
  package: '@danielng23/dsh-xry-host-system-metrics',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/listDirectory',
      service: 'systemMetrics',
      namespace: 'systemMetrics',
      method: 'listDirectory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/listDirectory:path',
            schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_listDirectory_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@danielng23/dsh-xry-host-system-metrics/types#DirectoryListing',
        schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_listDirectory_result$schema,
      },
      sourceLocation: {"file":"packages/host/system-metrics/src/index.ts","line":293,"column":9},
    },
    {
      id: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/overview',
      service: 'systemMetrics',
      namespace: 'systemMetrics',
      method: 'overview',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@danielng23/dsh-xry-host-system-metrics/types#SystemOverview',
        schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_overview_result$schema,
      },
      sourceLocation: {"file":"packages/host/system-metrics/src/index.ts","line":246,"column":9},
    },
    {
      id: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/readFile',
      service: 'systemMetrics',
      namespace: 'systemMetrics',
      method: 'readFile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/readFile:path',
            schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_readFile_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@danielng23/dsh-xry-host-system-metrics/types#FilePreview',
        schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_readFile_result$schema,
      },
      sourceLocation: {"file":"packages/host/system-metrics/src/index.ts","line":316,"column":9},
    },
    {
      id: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/runCommand',
      service: 'systemMetrics',
      namespace: 'systemMetrics',
      method: 'runCommand',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'command',
          wire: 'command',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/runCommand:command',
            schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_runCommand_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@danielng23/dsh-xry-host-system-metrics/types#CommandResult',
        schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_runCommand_result$schema,
      },
      sourceLocation: {"file":"packages/host/system-metrics/src/index.ts","line":402,"column":9},
    },
    {
      id: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/snapshot',
      service: 'systemMetrics',
      namespace: 'systemMetrics',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@danielng23/dsh-xry-host-system-metrics/types#SystemMetricsSnapshot',
        schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/host/system-metrics/src/index.ts","line":228,"column":3},
    },
    {
      id: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/writeFile',
      service: 'systemMetrics',
      namespace: 'systemMetrics',
      method: 'writeFile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/writeFile:path',
            schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_writeFile_parameter_0$schema,
          },
        },
        {
          name: 'content',
          wire: 'content',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@danielng23/dsh-xry-host-system-metrics#systemMetrics/writeFile:content',
            schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_writeFile_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@danielng23/dsh-xry-host-system-metrics/types#WriteResult',
        schema: _danielng23_dsh_xry_host_system_metrics_systemMetrics_writeFile_result$schema,
      },
      sourceLocation: {"file":"packages/host/system-metrics/src/index.ts","line":381,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Remote-only service exposing host resource snapshots to the browser. Every snapshot is projected directly from `node:os` at call time; no cache exists to synchronize.",
        "summary": "Remote-only service exposing host resource snapshots to the browser.",
        "tags": [
          {
            "name": "typert",
            "comment": "service systemMetrics",
            "text": "@typert service systemMetrics"
          }
        ],
        "jsDoc": "/**\n * Remote-only service exposing host resource snapshots to the browser. Every\n * snapshot is projected directly from `node:os` at call time; no cache exists\n * to synchronize.\n * @typert service systemMetrics\n */",
        "key": "systemMetrics",
        "exportName": "SystemMetricsService",
        "members": [
          {
            "kind": "method",
            "name": "snapshot",
            "signature": "@Remote('snapshot') snapshot(): SystemMetricsSnapshot",
            "summary": "Read the current host resource state.",
            "jsDoc": "/**\n * Read the current host resource state.\n * @returns load averages, since-boot CPU busy ratio, memory, and uptime.\n */"
          },
          {
            "kind": "method",
            "name": "overview",
            "signature": "@Remote('overview') async overview(): Promise<SystemOverview>",
            "summary": "Read the rich system overview for the left system panel: per-core CPU tick counts (the client computes usage deltas between polls), memory and swap, thermal/power/hardware (best-effort), and top processes.",
            "jsDoc": "/**\n * Read the rich system overview for the left system panel: per-core CPU\n * tick counts (the client computes usage deltas between polls), memory and\n * swap, thermal/power/hardware (best-effort), and top processes.\n * @returns the overview.\n */"
          },
          {
            "kind": "method",
            "name": "listDirectory",
            "signature": "@Remote('listDirectory') async listDirectory(path: string): Promise<DirectoryListing>",
            "summary": "List one directory for the filesystem browser.",
            "jsDoc": "/**\n * List one directory for the filesystem browser.\n * @param path - absolute directory to list.\n * @returns the listing (or an error string when unreadable).\n */"
          },
          {
            "kind": "method",
            "name": "readFile",
            "signature": "@Remote('readFile') async readFile(path: string): Promise<FilePreview>",
            "summary": "Read one file for the bottom-right preview pane / editor.",
            "jsDoc": "/**\n * Read one file for the bottom-right preview pane / editor. Text payloads\n * are capped at 4 MiB, images at 4 MiB, videos at 12 MiB; oversized files\n * are truncated and flagged rather than refused. Kind is decided by\n * extension with a UTF-8 sniff fallback for unknown extensions.\n * @param path - absolute file path.\n * @returns the preview payload (or an error string when unreadable).\n */"
          },
          {
            "kind": "method",
            "name": "writeFile",
            "signature": "@Remote('writeFile') async writeFile(path: string, content: string): Promise<WriteResult>",
            "summary": "Write one text file from the bottom-right editor.",
            "jsDoc": "/**\n * Write one text file from the bottom-right editor. Creates or replaces the\n * file at `path` with the given UTF-8 content; the parent directory must\n * exist. Trust surface matches `readFile`: the GUI already reads arbitrary\n * paths the host process can reach, so writing carries the same parity.\n * @param path - absolute file path.\n * @param content - full text content to persist.\n * @returns the write result (or an error string when unwritable).\n */"
          },
          {
            "kind": "method",
            "name": "runCommand",
            "signature": "@Remote('runCommand') async runCommand(command: string): Promise<CommandResult>",
            "summary": "Run one shell command for the bottom-right terminal panel.",
            "jsDoc": "/**\n * Run one shell command for the bottom-right terminal panel. Executes\n * `command` through `sh -c` with a 30s timeout and a 4 MiB output cap.\n * Non-zero exits return the captured output with the real exit code; a\n * command that cannot start (or times out) returns exitCode null.\n * Trust surface matches `writeFile`: the GUI already reads and writes\n * arbitrary paths the host process can reach, so executing commands the\n * operator types carries the same parity.\n * @param command - the shell command line to execute.\n * @returns captured stdout/stderr and the exit code.\n */"
          }
        ],
        "types": [
          {
            "name": "CommandResult",
            "declaration": "export interface CommandResult {\n    readonly stdout: string;\n    readonly stderr: string;\n    readonly exitCode: number | null;\n}"
          },
          {
            "name": "CoreTimes",
            "declaration": "export interface CoreTimes {\n    readonly user: number;\n    readonly nice: number;\n    readonly sys: number;\n    readonly idle: number;\n    readonly irq: number;\n}"
          },
          {
            "name": "DirectoryEntry",
            "declaration": "export interface DirectoryEntry {\n    readonly name: string;\n    readonly isDirectory: boolean;\n}"
          },
          {
            "name": "DirectoryListing",
            "declaration": "export interface DirectoryListing {\n    readonly path: string;\n    readonly entries: readonly DirectoryEntry[];\n    readonly error: string | null;\n}"
          },
          {
            "name": "FilePreview",
            "declaration": "export interface FilePreview {\n    readonly path: string;\n    readonly kind: 'text' | 'image' | 'video' | 'unsupported';\n    readonly mime: string;\n    readonly sizeBytes: number;\n    readonly truncated: boolean;\n    readonly text: string | null;\n    readonly dataUrl: string | null;\n    readonly error: string | null;\n}"
          },
          {
            "name": "HardwareInfo",
            "declaration": "export interface HardwareInfo {\n    readonly manufacturer: string;\n    readonly model: string;\n    readonly chassis: string;\n}"
          },
          {
            "name": "NetworkInfo",
            "declaration": "export interface NetworkInfo {\n    readonly interfaceName: string;\n    readonly state: string;\n    readonly ip: string | null;\n    readonly pingMs: number | null;\n    readonly rxBytes: number;\n    readonly txBytes: number;\n}"
          },
          {
            "name": "ProcessSample",
            "declaration": "export interface ProcessSample {\n    readonly pid: number;\n    readonly name: string;\n    readonly cpuPct: number;\n    readonly memPct: number;\n}"
          },
          {
            "name": "StorageInfo",
            "declaration": "export interface StorageInfo {\n    readonly path: string;\n    readonly totalBytes: number;\n    readonly usedBytes: number;\n    readonly usedPct: number;\n}"
          },
          {
            "name": "SystemMetricsSnapshot",
            "declaration": "export interface SystemMetricsSnapshot {\n    readonly loadavg: readonly [number, number, number];\n    readonly cpuBusyRatio: number;\n    readonly totalMemoryBytes: number;\n    readonly freeMemoryBytes: number;\n    readonly uptimeSeconds: number;\n    readonly timestamp: number;\n}"
          },
          {
            "name": "SystemOverview",
            "declaration": "export interface SystemOverview {\n    readonly timestamp: number;\n    readonly platform: string;\n    readonly uptimeSeconds: number;\n    readonly loadavg: readonly [number, number, number];\n    readonly memory: { readonly totalBytes: number; readonly usedBytes: number; };\n    readonly swap: { readonly totalBytes: number; readonly usedBytes: number; };\n    readonly cores: readonly CoreTimes[];\n    readonly thermalLevel: number | null;\n    readonly powerState: string | null;\n    readonly hardware: HardwareInfo;\n    readonly tasks: number;\n    readonly processes: readonly ProcessSample[];\n    readonly network: NetworkInfo;\n    readonly storage: StorageInfo;\n}"
          },
          {
            "name": "WriteResult",
            "declaration": "export interface WriteResult {\n    readonly path: string;\n    readonly sizeBytes: number;\n    readonly error: string | null;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
