/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CommandResult, DirectoryListing, FilePreview, SystemMetricsSnapshot, SystemOverview, WriteResult } from '@danielng23/dsh-xry-host-system-metrics/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73797374656d4d657472696373 {
    listDirectory: (path: string) => Promise<RemoteResult<DirectoryListing>>
    overview: () => Promise<RemoteResult<SystemOverview>>
    readFile: (path: string) => Promise<RemoteResult<FilePreview>>
    runCommand: (command: string) => Promise<RemoteResult<CommandResult>>
    snapshot: () => Promise<RemoteResult<SystemMetricsSnapshot>>
    writeFile: (path: string, content: string) => Promise<RemoteResult<WriteResult>>
  }
  interface TypertRemoteMap {
    'systemMetrics/listDirectory': (path: string) => Promise<RemoteResult<DirectoryListing>>
    'systemMetrics/overview': () => Promise<RemoteResult<SystemOverview>>
    'systemMetrics/readFile': (path: string) => Promise<RemoteResult<FilePreview>>
    'systemMetrics/runCommand': (command: string) => Promise<RemoteResult<CommandResult>>
    'systemMetrics/snapshot': () => Promise<RemoteResult<SystemMetricsSnapshot>>
    'systemMetrics/writeFile': (path: string, content: string) => Promise<RemoteResult<WriteResult>>
  }
  interface TypertRemoteNamespaceMap {
    'systemMetrics': TypertRemoteNamespace$73797374656d4d657472696373
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
