/**
 * Runtime hex-tile grid for the encom globe. The library ships a ~960 KB
 * precomputed grid (grid.js) generated by its buildgrid script from
 * hexasphere.js; generating the grid here with a lighter division level keeps
 * the bundle small while preserving the same tile geometry the globe's
 * particle shader expects (tiles with a 3D `b` boundary plus center lat/lon).
 */
import Hexasphere from 'hexasphere.js'

/** One hexasphere tile as the encom globe's particle builder consumes it. */
export interface GlobeTile {
  lat: number
  lon: number
  b: readonly { x: number; y: number; z: number }[]
}

/** Hexasphere construction radius (matches the library's own buildgrid). */
const HEX_RADIUS = 30
/** Division level: 16 → ~2.5k tiles, right for the compact world-view pane. */
const HEX_DIVISIONS = 16
/** Hexagon edge inset factor (gap between tiles). */
const HEX_SIZE = 0.45
/** Scale the radius-30 hexasphere up to the encom camera's ~500-unit sphere. */
const WORLD_SCALE = 500 / HEX_RADIUS

/**
 * Build the globe's hex-tile grid. Per-tile edge shrink varies slightly so
 * the surface keeps the organic encom look instead of a uniform mesh.
 * @returns tiles for the Globe `tiles` option.
 */
export function generateGlobeTiles(): GlobeTile[] {
  const hexasphere = new Hexasphere(HEX_RADIUS, HEX_DIVISIONS, HEX_SIZE)
  const tiles: GlobeTile[] = []
  for (const tile of hexasphere.tiles) {
    const center = tile.centerPoint
    // The encom buildgrid derives this from map darkness; a bounded random
    // factor reproduces the same visual variety without the map.
    const inset = 0.45 + Math.random() * 0.4
    const b = tile.boundary.map((point) => {
      const segment = point.segment(center, inset)
      return {
        x: Number(segment.x) * WORLD_SCALE,
        y: Number(segment.y) * WORLD_SCALE,
        z: Number(segment.z) * WORLD_SCALE,
      }
    })
    const latLon = tile.getLatLon(HEX_RADIUS)
    tiles.push({ lat: latLon.lat, lon: latLon.lon, b })
  }
  return tiles
}
